<?php
session_start();
// Load the environment configuration file generated by the setup wizard
if (file_exists('config.php')) {
    require_once('config.php');
} else {
    die("Application is not configured. Please run upgrade_db.php first.");
}

if (!isset($_SESSION['staff'])) {
    header("Location: login.php");
    exit;
}
include('db/db.php');

// ... rest of your index.php code remains identical ...

// Fetch settings
$settings_result = $conn->query("SELECT * FROM settings");
$settings = [];
while ($row = $settings_result->fetch_assoc()) {
    $settings[$row['setting_key']] = $row['setting_value'];
}
define('MAX_USAGE_MINUTES', $settings['max_usage_minutes']);

// 🧠 ALL form actions go here BEFORE any output (no HTML printed yet)

if (isset($_POST['register'])) {
    $stmt = $conn->prepare("INSERT INTO students (fullname, student_number, course) VALUES (?, ?, ?)");
    $stmt->bind_param("sss", $_POST['fullname'], $_POST['student_number'], $_POST['course']);
    $stmt->execute();
    header("Location: index.php");
    exit;
}

// Time-in logic
if (isset($_POST['timein'])) {
    $stmt = $conn->prepare("INSERT INTO sessions (student_id, time_in) VALUES (?, NOW())");
    $stmt->bind_param("i", $_POST['student_id']);
    $stmt->execute();
    header("Location: index.php");
}

// Time-out logic
// Time-out logic (Handles buttons and Auto-Kick AJAX)
if (isset($_POST['timeout'])) {
    $sid = intval($_POST['session_id']);
    
    // Ensure the session is actually active before timing out
    $check_active = $conn->query("SELECT student_id FROM sessions WHERE id=$sid AND time_out IS NULL")->fetch_assoc();
    if ($check_active) {
        $conn->query("UPDATE sessions SET time_out=NOW(), session_minutes=TIMESTAMPDIFF(MINUTE, time_in, NOW()) WHERE id=$sid");
        
        // Add to student's total
        $sess = $conn->query("SELECT student_id, session_minutes FROM sessions WHERE id=$sid")->fetch_assoc();
        $conn->query("UPDATE students SET total_time_minutes = total_time_minutes + {$sess['session_minutes']}, session_count = session_count + 1 WHERE id={$sess['student_id']}");
    }
    
    // If it's a JavaScript background kick, stop processing right here
    if (!empty($_SERVER['HTTP_X_REQUESTED_WITH']) || isset($_POST['ajax'])) {
        echo json_encode(['status' => 'success']);
        exit;
    }
    
    header("Location: index.php");
    exit;
}

// Reset logic
if (isset($_POST['reset'])) {
    $sid = $_POST['reset_id'];
    // Reset total time and session count
    $conn->query("UPDATE students SET total_time_minutes = 0, session_count = 0 WHERE id = $sid");
    // Delete all sessions (or just clear recent)
    $conn->query("DELETE FROM sessions WHERE student_id = $sid");
    header("Location: index.php");
}

// Delete logic
if (isset($_POST['delete'])) {
    $sid = $_POST['delete_id'];
    $conn->query("DELETE FROM students WHERE id = $sid");
    header("Location: index.php");
    exit;
}

if (isset($_POST['timeout']) && isset($_POST['session_id'])) {
    $session_id = intval($_POST['session_id']);
    $now = date('Y-m-d H:i:s');

    $stmt = $conn->prepare("SELECT time_in, student_id FROM sessions WHERE id = ? AND time_out IS NULL");
    $stmt->bind_param("i", $session_id);
    $stmt->execute();
    $stmt->bind_result($time_in, $student_id);

    if ($stmt->fetch()) {
        $stmt->close();

        $minutes = round((strtotime($now) - strtotime($time_in)) / 60);
        if ($minutes < 1) $minutes = 1;

        // Update session
        $update = $conn->prepare("UPDATE sessions SET time_out = ?, session_minutes = ? WHERE id = ?");
        $update->bind_param("sii", $now, $minutes, $session_id);
        $update->execute();
        $update->close();

        // Deduct from student remaining and increment session count
        $conn->query("UPDATE students SET remaining_minutes = GREATEST(0, remaining_minutes - $minutes), session_count = session_count + 1 WHERE id = $student_id");
    } else {
        $stmt->close();
    }

    // Exit to avoid HTML output on AJAX
    if (!empty($_SERVER['HTTP_X_REQUESTED_WITH'])) exit;
}

// Check if a single user was checked, or if the global Batch Check was clicked
$checkedSessionId = isset($_POST['check_time']) && isset($_POST['session_id']) ? $_POST['session_id'] : null;
$isBatchCheck = isset($_POST['batch_check']);
?>
<!DOCTYPE html>
<html>
<head>
    <title>E-Station Tracker</title>
    <link rel="stylesheet" href="assets/css/style.css">
    <link rel="stylesheet" href="assets/css/dark-mode.css">
</head>
<body>
    <div id="theme-switcher">🌓</div>

    <div class="header">
        <img src="uploads/<?= $settings['school_logo'] ?? 'logo.png' ?>" alt="School Logo">
        <h1><?= $settings['school_name'] ?? 'E-Station School' ?></h1>
    </div>

<h1>📘 E-Station Time Log</h1>

<p style="text-align:right;">
    Logged in as <strong><?= $_SESSION['staff'] ?> (<?= $_SESSION['role'] ?>)</strong> |
    <?php if ($_SESSION['role'] === 'admin'): ?>
        <a href="admin.php">👑 Admin</a> |
    <?php endif; ?>
    <a href="logout.php">🚪 Logout</a>
</p>

<form method="post">
    <h2>Register Student</h2>
    <input name="fullname" placeholder="Fullname" required>
    <input name="student_number" placeholder="Student Number" required>
    <input name="course" placeholder="Course" required>
    <button name="register">Register</button>
</form>
</br>
</br>

<form method="get">
    <h2>Search Student</h2>
    <input name="query" placeholder="Search by name or student number">
    <button>Search</button>
</form>

<div style="margin: 20px 0; text-align: right;">
    <form method="post" style="display:inline">
        <button type="submit" name="batch_check" style="background-color: #17a2b8; color: white; font-weight: bold; padding: 10px 15px; border: none; border-radius: 4px; cursor: pointer;">
            🔍 Batch Check All Active
        </button>
    </form>
</div>

<?php
$search = isset($_GET['query']) ? "%" . $_GET['query'] . "%" : "%";
$stmt = $conn->prepare("SELECT * FROM students WHERE fullname LIKE ? OR student_number LIKE ?");
$stmt->bind_param("ss", $search, $search);
$stmt->execute();
$result = $stmt->get_result();
?>

<table>
    <thead>
        <tr>
            <th>-</th>
            <th>Fullname</th>
            <th>Student No.</th>
            <th>Course</th>
            <th>Sessions</th>
            <th>Total Time Used</th>
            <th>Remaining Time</th>
            <th>Status</th>
            <th>Action</th>
            <th>Time Used</th>
        </tr>
    </thead>
    <tbody>

<?php
			while ($row = $result->fetch_assoc()) {
            $sid = $row['id'];
            $active = $conn->query("SELECT * FROM sessions WHERE student_id=$sid AND time_out IS NULL")->fetch_assoc();
            $used = $row['total_time_minutes'];
            $MAX_MINUTES = MAX_USAGE_MINUTES; 
            $remaining_minutes = max(0, $MAX_MINUTES - $used);

            // Calculate active session time right now to deduct from remaining time on page load
            $current_session_seconds = 0;
            if ($active) {
                $timeIn = new DateTime($active['time_in']);
                $now = new DateTime();
                $current_session_seconds = $now->getTimestamp() - $timeIn->getTimestamp();
            }

            // Exact seconds left before the student hits absolute zero
            $total_seconds_left = ($remaining_minutes * 60) - $current_session_seconds;
            if ($total_seconds_left < 0) $total_seconds_left = 0;

            // STATUS FIX: Prioritize Active over Blocked so the row renders correctly while open
            if ($active) {
                $status = "🟢 Active";
            } elseif ($used >= $MAX_MINUTES) {
                $status = "🚫 Blocked";
            } else {
                $status = "⚪ Idle";
            }

            // Tag the row with custom data attributes for JavaScript to read
            echo "<tr class='student-row' data-session-id='" . ($active['id'] ?? '') . "' data-seconds-left='$total_seconds_left' data-status='$status'>";

            if ($_SESSION['role'] === 'admin') {
                echo "<td><form method='post' style='display:inline' onsubmit=\"return confirm('Are you sure you want to delete this student?');\">
                        <input type='hidden' name='delete_id' value='$sid'>
                        <button name='delete' class='delete-btn'>🗑 ️</button>
                </form></td>";
            } else {
                echo "<td></td>";
            }

            echo "<td>{$row['fullname']}</td>";
            echo "<td>{$row['student_number']}</td>";
            echo "<td>{$row['course']}</td>";
            echo "<td>{$row['session_count']}</td>";
            echo "<td>" . floor($used/60) . "h " . ($used%60) . "m</td>";
            echo "<td>" . floor($remaining_minutes/60) . "h " . ($remaining_minutes%60) . "m</td>";
            echo "<td>$status</td>";

            echo "<td>";

						$timeUsed = '';
							if ($active) {
									echo "<form data-session-id='" . $active['id'] . "' class='timeout-form' method='post' style='display:inline'>
													<input type='hidden' name='session_id' value='" . $active['id'] . "'>
													<button name='timeout' class='timeout-btn'>⏹️ Time-Out</button>
									</form>";

									// MODIFIED: Trigger calculation if single checked OR if global Batch Check is active
									if ((isset($checkedSessionId) && $active['id'] == $checkedSessionId) || $isBatchCheck) {
											
											$check_stmt = $conn->prepare("SELECT time_in FROM sessions WHERE student_id = ? AND time_out IS NULL ORDER BY time_in DESC LIMIT 1");
											$check_stmt->bind_param("i", $active['student_id']);
											$check_stmt->execute();
											$check_result = $check_stmt->get_result();

											if ($check_row = $check_result->fetch_assoc()) {
													$timeIn = new DateTime($check_row['time_in']);
													$now = new DateTime();
													$interval = $timeIn->diff($now);
													$timeUsed = $interval->format('%h hrs %i mins %s secs');
											} else {
													$timeUsed = "N/A";
											}
											$check_stmt->close();
									}

							} else {
									if ($used >= MAX_USAGE_MINUTES) {
											echo "<span style='color: red; font-weight: bold'>🚫 Blocked</span>";
									} else {
											echo "<form method='post' style='display:inline'>
															<input type='hidden' name='student_id' value='$sid'>
															<button name='timein'>▶️ Time-In</button>
											</form>";
									}
							}
?>
            <?php if ($_SESSION['role'] === 'admin'): ?>
                <form method='post' style='display:inline' onsubmit="return confirm('⚠️ Are you sure you want to RESET TOTAL USAGE TIME?')">
                    <input type='hidden' name='reset_id' value='<?= $sid ?>'>
                    <button name='reset' class='reset-btn'>🔄 Reset</button>
                </form>
            <?php endif; ?>

            <form method="post" style="display:inline">
                <input type="hidden" name="session_id" value="<?php echo $active['id'] ?? ''; ?>">
                <button type="submit" name="check_time">✅ Check</button>
            </form>

<?php
            echo "</td>";
            echo "<td>$timeUsed</td>"; 
            echo "</tr>";
        }
?>

    </tbody>
</table>
<br><br>
<button id="power-failure-trigger" >⚠️ Power Failure Logout</button>

<a href="print_report.php" target="_blank">
    <button>📄 Printable Report</button>
</a>

    <div class="footer">
        <p>&copy; <?= date('Y') ?> <?= $settings['school_name'] ?? 'E-Station School' ?></p>
    </div>

<script src="assets/js/script.js"></script>
<script>
document.getElementById("power-failure-trigger").addEventListener("click", () => {
    const buttons = document.querySelectorAll(".timeout-form");
    let index = 0;

    async function clickNext() {
        if (index < buttons.length) {
            const form = buttons[index];
            const sessionId = form.getAttribute("data-session-id");

            if (sessionId) {
                await fetch("index.php", {
                    method: "POST",
                    headers: {
                        "Content-Type": "application/x-www-form-urlencoded",
                    },
                    body: "session_id=" + encodeURIComponent(sessionId) + "&timeout=1"
                });
            }

            index++;
            setTimeout(clickNext, 1000);
        } else {
            alert("Power failure logout completed.");
            location.reload();
        }
    }

    if (buttons.length === 0) {
        alert("No active users to log out.");
    } else {
        clickNext();
    }
});
</script>
<script>
document.addEventListener("DOMContentLoaded", () => {
    // Run the checker every 5 seconds for snappy updates
    setInterval(checkLiveSessions, 5000);

    function checkLiveSessions() {
        const rows = document.querySelectorAll(".student-row");

        rows.forEach(row => {
            const status = row.getAttribute("data-status");
            const sessionId = row.getAttribute("data-session-id");
            
            if (status === "🟢 Active" && sessionId) {
                let secondsLeft = parseInt(row.getAttribute("data-seconds-left")) - 5;
                if (secondsLeft < 0) secondsLeft = 0;
                
                // Update the hidden tracker attribute
                row.setAttribute("data-seconds-left", secondsLeft);

                // Target the "Time Used" column to update live countdown visual indicators optionally,
                // But most importantly: Kick if time reaches 0!
                if (secondsLeft <= 0) {
                    autoKickUser(sessionId, row);
                }
            }
        });
    }

    async function autoKickUser(sessionId, row) {
        // Prevent multiple simultaneous triggers for the same user
        row.setAttribute("data-status", "🚫 Kicking..."); 
        
        console.log(`Auto-kick triggered for Session ID: ${sessionId}`);

        // Send a silent background POST request to index.php to close the session
        const formData = new FormData();
        formData.append("session_id", sessionId);
        formData.append("timeout", "1");
        formData.append("ajax", "1");

        try {
            await fetch("index.php", {
                method: "POST",
                body: formData,
                headers: {
                    'X-Requested-With': 'XMLHttpRequest'
                }
            });
            
            // Refresh the dashboard display data instantly without reloading the whole page window
            location.reload(); 
        } catch (error) {
            console.error("Auto-kick failed network transmission:", error);
        }
    }
});
</script>
</body>
</html>