<?php
session_start();
if (!isset($_SESSION['staff'])) {
    header("Location: login.php");
    exit;
}

include('db/db.php');
// date_default_timezone_set('Asia/Manila');

// Fetch settings
$settings_result = $conn->query("SELECT * FROM settings");
$settings = [];
while ($row = $settings_result->fetch_assoc()) {
    $settings[$row['setting_key']] = $row['setting_value'];
}
define('MAX_USAGE_MINUTES', $settings['max_usage_minutes']);


// Fetch all students
$result = $conn->query("SELECT * FROM students ORDER BY fullname ASC");
?>
<!DOCTYPE html>
<html>
<head>
    <title>E-Station Usage Report</title>
    <link rel="stylesheet" href="assets/css/style.css">
    <link rel="stylesheet" href="assets/css/dark-mode.css">
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
        }
        h2 {
            text-align: center;
            margin-bottom: 5px;
        }
        .meta {
            text-align: center;
            margin-bottom: 15px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
        }
        th, td {
            border: 1px solid #000;
            padding: 6px;
            text-align: center;
        }
        th {
            background: #f0f0f0;
						color: #222;
        }
        @media print {
            button, #theme-switcher {
                display: none;
            }
        }
    </style>
</head>
<body>
    <div id="theme-switcher">🌓</div>

    <div class="header">
        <img src="uploads/<?= $settings['school_logo'] ?? 'logo.png' ?>" alt="School Logo">
        <h1><?= $settings['school_name'] ?? 'E-Station School' ?></h1>
    </div>

<h2>📘 E-Station Usage Report</h2>
<div class="meta">
    <!-- Generated by: <strong><?= $_SESSION['staff'] ?></strong><br> -->
    Date: <?= date('F d, Y h:i A') ?>
</div>

<button onclick="window.print()">🖨️ Print Report</button>

<table>
    <thead>
        <tr>
            <th>#</th>
            <th>Fullname</th>
            <th>Course</th>
            <th>Sessions</th>
            <th>Total Time Used</th>
            <th>Remaining Time</th>
            <th>Status</th>
        </tr>
    </thead>
    <tbody>
<?php
$count = 1;
while ($row = $result->fetch_assoc()) {

    $used = (int)$row['total_time_minutes'];
    $remaining = max(0, MAX_USAGE_MINUTES - $used);

    // Check active session
    $active = $conn->query(
        "SELECT id FROM sessions
         WHERE student_id={$row['id']} AND time_out IS NULL"
    )->fetch_assoc();

    if ($used >= MAX_USAGE_MINUTES) {
        $status = "🚫 Time's up";
    } else {
        $status = "✅ Allowed";
    }

    echo "<tr>";
    echo "<td>{$count}</td>";
    echo "<td>{$row['fullname']}</td>";
    echo "<td>{$row['course']}</td>";
    echo "<td>{$row['session_count']}</td>";
    echo "<td>" . floor($used / 60) . "h " . ($used % 60) . "m</td>";
    echo "<td>" . floor($remaining / 60) . "h " . ($remaining % 60) . "m</td>";
    echo "<td>{$status}</td>";
    echo "</tr>";

    $count++;
}
?>
    </tbody>
</table>

    <div class="footer">
        <p>&copy; <?= date('Y') ?> <?= $settings['school_name'] ?? 'E-Station School' ?></p>
    </div>

    <script src="assets/js/script.js"></script>
</body>
</html>