<?php
session_start();
if (!isset($_SESSION['staff'])) {
    header("Location: login.php");
    exit;
}

include('db/db.php');
// date_default_timezone_set('Asia/Manila');

// Fetch max usage minutes from settings
$settings_result = $conn->query("SELECT setting_value FROM settings WHERE setting_key = 'max_usage_minutes'");
$max_usage_minutes = $settings_result->fetch_assoc()['setting_value'];
define('MAX_USAGE_MINUTES', $max_usage_minutes);

// Fetch all students
$result = $conn->query("SELECT * FROM students ORDER BY fullname ASC");
?>
<!DOCTYPE html>
<html>
<head>
    <title>E-Station Usage Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
        }
        h2 {
            text-align: center;
            margin-bottom: 5px;
        }
        .meta {
            text-align: center;
            margin-bottom: 15px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
        }
        th, td {
            border: 1px solid #000;
            padding: 6px;
            text-align: center;
        }
        th {
            background: #f0f0f0;
        }
        @media print {
            button {
                display: none;
            }
        }
    </style>
</head>
<body>

<h2>📘 E-Station Usage Report</h2>
<div class="meta">
    <!-- Generated by: <strong><?= $_SESSION['staff'] ?></strong><br> -->
    Date: <?= date('F d, Y h:i A') ?>
</div>

<button onclick="window.print()">🖨️ Print Report</button>

<table>
    <thead>
        <tr>
            <th>#</th>
            <th>Fullname</th>
            <th>Course</th>
            <th>Total Time Used</th>
            <th>Remaining Time</th>
            <th>Status</th>
        </tr>
    </thead>
    <tbody>
<?php
$count = 1;
while ($row = $result->fetch_assoc()) {

    $used = (int)$row['total_time_minutes'];
    $remaining = max(0, MAX_USAGE_MINUTES - $used);

    // Check active session
    $active = $conn->query(
        "SELECT id FROM sessions
         WHERE student_id={$row['id']} AND time_out IS NULL"
    )->fetch_assoc();

    if ($used >= MAX_USAGE_MINUTES) {
        $status = "🚫 Time's up";
    } else {
        $status = "✅ Allowed";
    }

    echo "<tr>";
    echo "<td>{$count}</td>";
    echo "<td>{$row['fullname']}</td>";
    echo "<td>{$row['course']}</td>";
    echo "<td>" . floor($used / 60) . "h " . ($used % 60) . "m</td>";
    echo "<td>" . floor($remaining / 60) . "h " . ($remaining % 60) . "m</td>";
    echo "<td>{$status}</td>";
    echo "</tr>";

    $count++;
}
?>
    </tbody>
</table>

</body>
</html>